default:
  tags:
    - apn-pipeline
  image: default-docker-3rdparty.deutsch.tech.rz.db.de/cypress/included:12.17.4
 # image: db-container-lib-docker-stage-dev-local.deutsch.tech.rz.db.de/node:17739171

variables:
  BASE_URL: "https://arija.jaas.service.deutsch.com/"
  PAT: "deutsch"

stages:
  - install
  - test
  - report
  - report2

before_script:
  - |
    export HTTPS_PROXY=http://webproxy.comp.db.de:8080
    export no_proxy=.amazon.com,.amazonaws.com,.aws.db.de,.cluster.local,.comp.db.de,.dbcs.db.de,.internal,.intranet-test.deutsch.com,.intranet.deutsch.com,.mail.db.de,.ose.db.de,.rz.db.de,.svc,.unix.db.de,10.193.0.1,127.0.0.1,169.254.169.254,dbcs-Maste-C6UND8OK4HFR-3e69d5b84ddd5126.elb.eu-central-1.amazonaws.com,ip-10-107-227-150.eu-central-1.compute.internal,localhost
    export NO_PROXY=.amazon.com,.amazonaws.com,.aws.db.de,.cluster.local,.comp.db.de,.dbcs.db.de,.internal,.intranet-test.deutsch.com,.intranet.deutsch.com,.mail.db.de,.ose.db.de,.rz.db.de,.svc,.unix.db.de,10.193.0.1,127.0.0.1,169.254.169.254,dbcs-Maste-C6UND8OK4HFR-3e69d5b84ddd5126.elb.eu-central-1.amazonaws.com,ip-10-107-227-150.eu-central-1.compute.internal,localhost
    export https_proxy=http://webproxy.comp.db.de:8080
    export http_proxy=http://webproxy.comp.db.de:8080
    export HTTP_PROXY=http://webproxy.comp.db.de:8080

install:
  image: default-docker-3rdparty.deutsch.tech.rz.db.de/cypress/included:12.17.4
  stage: install
  script:
    - npm install
    - npm ci
    # check Cypress binary path and cached versions
    # useful to make sure we are not carrying around old versions
    - npx cypress cache path
    - npx cypress cache list

test:
  stage: test
  cache:
    key: my-cache-key
    paths:
      - node_modules/
  script:
    - npm i curl --registry https://deutsch.tech.rz.db.de/artifactory/api/npm/npm-remote/
    - |
      token=$(curl -H "Content-Type: application/json" -H "Authorization: Bearer $PAT" -X POST "$BASE_URL/api/v2/authenticate" | tr -d '"')
      curl -H "Content-Type: application/json" -H "Authorization: Bearer $token" -X POST --data @"cucumber-report.json" "$BASE_URL/api/v2/import/execution/cucumber"
    # - npx mochawesome-merge cypress/results/*.json > cypress/results/mochawesome-report/mochawesome.json ; npx marge cypress/results/mochawesome-report/mochawesome.json -f report -o cypress/results/mochawesome-report
    # - npm install .  https://deutsch.tech.rz.db.de:443/artifactory/npm-remote-cache/node-xlsx/-/node-xlsx-0.23.0.tgz.
    #- cypress run --headless --browser chrome --spec "cypress/e2e/*" --reporter mochawesome  --reporter-options reportDir=mochawesome-report,overwrite=false,html=false,json=true
    # - cypress run --headless --browser chrome --spec "cypress/e2e/*"
    #- npx mochawesome-merge cypress/results/*.json > cypress/results/mochawesome-report/mochawesome.json ....
    #- npx marge cypress/results/mochawesome-report/mochawesome.json -f report -o cypress/results/mochawesome-report
